---
title: "`DISCent` Validation Report"
author: "Nicholas F. Brazeau"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    highlight: textmate
    theme: lumen
    toc: yes
    toc_float: yes
    toc_depth: 3
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F, eval = T, results = 'hide',
                      fig.align = 'center', fig.width = 6, fig.height = 6)
knitr::opts_knit$set(root.dir = here::here("validation"))
options(tidyverse.quiet = TRUE)

```



```{r}
library(targets)
tar_load("results", store = "/Users/nbrazeau/Documents/Github/discent/validation")
```



# DISC Result Values
```{r}
retvals <- results %>% 
  dplyr::select(c("modname", "discret")) %>% 
  dplyr::mutate(deme = purrr::map(discret, "deme_key"),
                deme = purrr::map(deme, "Deme"),
                fvals = purrr::map(discret, "Final_Fis"),
                finalm = purrr::map(discret, "Final_m")) %>% 
  tidyr::unnest(cols = c(deme, fvals, finalm))

retvals %>% 
  dplyr::mutate(demefact = factor(deme, levels = as.character(c(1,11,58,61,64,111,121)))) %>% 
  ggplot() +
  geom_boxplot(aes(x = demefact, y = fvals, group = demefact),
               outlier.colour = "red", outlier.shape=8,
               outlier.size=4) +
  ylab("DISC Values") + xlab("Deme") + 
  theme_linedraw() +
  facet_wrap(~modname) + 
  theme(plot.title = element_text(family = "Helvetica", face = "bold", hjust = 0.5, size = 14),
        axis.title = element_text(family = "Helvetica", face = "bold", hjust = 0.5, size = 12),
        axis.text.y = element_text(family = "Helvetica", hjust = 0.5, size = 11),
        axis.text.x = element_text(family = "Helvetica", hjust = 1, size = 11, angle = 45))


```


# Final Ms Result Values
```{r}
retvals %>% 
  ggplot() +
  geom_boxplot(aes(y = finalm),
               outlier.colour = "blue", outlier.shape=8,
               outlier.size=4) +
  ylab("Final Migration Values") +  
  theme_linedraw() +
  facet_wrap(~modname) + 
  theme(plot.title = element_text(family = "Helvetica", face = "bold", hjust = 0.5, size = 14),
        axis.title = element_text(family = "Helvetica", face = "bold", hjust = 0.5, size = 12),
        axis.text.y = element_text(family = "Helvetica", hjust = 0.5, size = 11),
        axis.text.x = element_text(family = "Helvetica", hjust = 1, size = 11, angle = 45))


```


# Network Results
```{r}

get_centrality_disc <- function(discdat, discret) {
  
  # smpl deme key
  smpldemekey <- tibble::tibble(name = as.character(c(discdat$smpl1, discdat$smpl2)),
                                deme = as.character(c(discdat$deme1, discdat$deme2)))
  
  # get centrality per deme
  eigencent <- discdat %>% 
    tidygraph::as_tbl_graph() %>% 
    dplyr::mutate(cent = tidygraph::centrality_eigen(weights = gendist)) %>%
    tidygraph::activate("nodes") %>%
    tibble::as_tibble() %>% 
    dplyr::left_join(., smpldemekey, by = "name") %>% 
    dplyr::group_by(deme) %>% 
    dplyr::summarise(
       meancent = mean(cent)
    )
  
  # disc values
  disctab <- tibble::tibble(deme = discret$deme_key$Deme,
                            disc = discret$Final_Fis)
  
  # out 
  out <- dplyr::full_join(eigencent, disctab, by = "deme")
  return(out)
}


#......................
# get vals
#......................
netret <- results %>% 
  dplyr::select(c("modname", "discdat", "discret")) %>% 
  dplyr::mutate(netvals = purrr::map2(discdat, discret, get_centrality_disc)) %>% 
  dplyr::select(c("modname", "netvals")) %>% 
  tidyr::unnest(cols = c(netvals))

#......................
# plot out
#......................
netret %>% 
  ggplot() + 
  geom_point(aes(x = meancent, y = disc, color = deme)) + 
  scale_color_viridis_d() + 
  facet_wrap(~modname)
```
