# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vanilla_deme_inbreeding_coef_cpp <- function(args) {
    .Call(`_discent_vanilla_deme_inbreeding_coef_cpp`, args)
}

